apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-hello-world.fullname" . }}
  labels:
    {{- include "go-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "go-hello-world.selectorLabels" . | nindent 4 }}
