{{- if eq (include "pico-agent.createSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pico-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pico-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.webhook.secret | quote }}
{{- end }}
