apiVersion: v2
name: otlp-gateway
description: Helm chart that deploys otlp-gateway
type: application
version: 0.0.3
appVersion: "v0.3.0"
keywords:
  - otlp
  - gateway
  - opentelemetry
sources:
  - https://github.com/loafoe/caddy-token
