{{- range .Values.mcpInstances }}
{{- if and .tokenSecret.create .tokenSecret.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .tokenSecret.name }}"
  labels:
    {{- include "mt-mcp-grafana.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{ .tokenSecret.key | default "token" }}: "{{ .tokenSecret.value }}"
{{- end }}
{{- end }}
