apiVersion: v2
name: patch-operator
description: Helm chart that deploys patch-operator
type: application
version: 0.11.4
appVersion: "v0.11.1"
keywords:
  - volume
  - storage
  - csi
  - expansion
  - monitoring
sources:
  - https://github.com/redhat-cop/patch-operator
