apiVersion: v1
name: patch-operator
version: v0.11.3
appVersion: v0.11.1
description: Helm chart that deploys patch-operator
keywords:
  - volume
  - storage
  - csi
  - expansion
  - monitoring
sources:
  - https://github.com/redhat-cop/patch-operator
engine: gotpl
