{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) (not .Values.provisioning.enabled) }}
{{- if .Values.auth.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-ocpp-server.fullname" . }}-credentials
  labels:
    {{- include "go-ocpp-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.json: {{ .Values.auth.credentials | toJson | quote }}
{{- end }}
{{- end }}
