apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-ocpp-server.fullname" . }}
  labels:
    {{- include "go-ocpp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ocpp
      protocol: TCP
      name: ocpp
  selector:
    {{- include "go-ocpp-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-ocpp-server.fullname" . }}-api
  labels:
    {{- include "go-ocpp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "go-ocpp-server.selectorLabels" . | nindent 4 }}
