{{- if and .Values.api.clientSecretValue (not .Values.api.clientSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pico-mcp.fullname" . }}-oauth2
  labels:
    {{- include "pico-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.api.clientSecretValue | quote }}
{{- end }}
