{{- $api := .Values.api | default dict -}}
{{- if and $api.clientSecretValue (not $api.clientSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "centcom.fullname" . }}-oauth2
  labels:
    {{- include "centcom.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ $api.clientSecretValue | quote }}
{{- end }}
