apiVersion: v2
name: centcom
description: MCP server for managing multiple centcom-satellite instances
type: application
version: 0.54.0
appVersion: "v0.74.0"
keywords:
  - kubernetes
  - mcp
  - spiffe
  - ai
home: https://github.com/loafoe/centcom
maintainers:
  - name: Andy Lo-A-Foe
    email: andy.lo-a-foe@philips.com
