name: Helm Publish (OCI)

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm.yaml'
      - '.github/actions/action-helm-chart-repo/**'
  workflow_dispatch:

jobs:
  helm:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Build and Push the Helm Charts to GitHub Container Registry
        uses: ./.github/actions/action-helm-chart-repo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chartsPath: ./charts/
